export const mockJobOrders = [
    {
        orderName: "Agile Product Owner Sr Advisor",
        orderDate: "07.02.2025",
        subDate: "07.02.2025",
        client: "Cigna",
        status: "Active",
        tSourced: "Senthil",
        subBy: "Anita",
        candidate: "Komal Kumari Nahata",
        clientRecruiter: "Balaji",
        candidateStatus: "More of BA candidate, need Product Owner experience",
        feedback: "",
        comments: ""
    },
    {
        orderName: "Agile Product Owner Sr Advisor",
        orderDate: "07.02.2025",
        subDate: "07.02.2025",
        client: "Cigna",
        status: "Hold",
        tSourced: "Mani",
        subBy: "Breme",
        candidate: "Ankita Ashok Said Patil",
        clientRecruiter: "Balaji",
        candidateStatus: "25 Aug start date // on boarding",
        feedback: "",
        comments: "Cleared second round on Jul 30"
    },
    {
        orderName: "Project Manager",
        orderDate: "07.09.2025",
        subDate: "07.09.2025",
        client: "Comerica",
        status: "Active",
        tSourced: "Senthil",
        subBy: "Anita",
        candidate: "Rathina Kumar Ramamoorthi",
        clientRecruiter: "Jason",
        candidateStatus: "Banking Exp too old",
        feedback: "",
        comments: ""
    },
    {
        orderName: "Sr. Penetration Test Coordinator",
        orderDate: "07.10.2025",
        subDate: "07.11.2025",
        client: "Comerica",
        status: "Active",
        tSourced: "Mani",
        subBy: "Breme",
        candidate: "Arunchand Kakkireni",
        clientRecruiter: "Kari",
        candidateStatus: "Only USC or GC, no sponsorship",
        feedback: "",
        comments: ""
    },
    {
        orderName: "Tableau Developer",
        orderDate: "07.14.2025",
        subDate: "07.15.2025",
        client: "Huntington",
        status: "Active",
        tSourced: "Senthil",
        subBy: "Anita",
        candidate: "Amrin Syed",
        clientRecruiter: "Jason",
        candidateStatus: "Pipeline - Position is halted",
        feedback: "",
        comments: ""
    },
    {
        orderName: "Data Engineer",
        orderDate: "07.14.2025",
        subDate: "07.15.2025",
        client: "BCBSM",
        status: "Active",
        tSourced: "Philip",
        subBy: "Anita",
        candidate: "Sai Soorya Sulur",
        clientRecruiter: "Saravanan",
        candidateStatus: "Start date 14 Jul // on boarding",
        feedback: "",
        comments: ""
    },
    {
        orderName: "Workday Integration",
        orderDate: "07.17.2025",
        subDate: "07.17.2025",
        client: "RIT",
        status: "Active",
        tSourced: "Philip",
        subBy: "Anita",
        candidate: "Prashanthi Katta",
        clientRecruiter: "Margie",
        candidateStatus: "Re-submitted with Azure exp",
        feedback: "",
        comments: ""
    },
    {
        orderName: "Application Developer",
        orderDate: "07.21.2025",
        subDate: "07.21.2025",
        client: "BCBSM",
        status: "Active",
        tSourced: "Anita",
        subBy: "Anita",
        candidate: "Vignesh Adithya",
        clientRecruiter: "Saravanan",
        candidateStatus: "Submitted to client and position cancelled",
        feedback: "",
        comments: ""
    },
    {
        orderName: "IT Test Coordinator",
        orderDate: "07.24.2025",
        subDate: "07.24.2025",
        client: "Comerica",
        status: "Active",
        tSourced: "Philip",
        subBy: "Anita",
        candidate: "Reddy Shankar Kande",
        clientRecruiter: "Balaji",
        candidateStatus: "Submitted to client",
        feedback: "",
        comments: ""
    },
    {
        orderName: "Tech Architect",
        orderDate: "07.24.2025",
        subDate: "07.24.2025",
        client: "Comerica",
        status: "Active",
        tSourced: "Senthil",
        subBy: "Anita",
        candidate: "Rajkumar Rajadurai",
        clientRecruiter: "Saravanan",
        candidateStatus: "Submitted to client",
        feedback: "",
        comments: ""
    }
];
