export const quotes = [
    "Success is the sum of small efforts, repeated day in and day out. – Robert Collier",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Great things come from hard work and perseverance. No excuses. – Kobe Bryant",
    "Dreams don’t work unless you do. – John C. Maxwell",
    "Push yourself, because no one else is going to do it for you.",
    "Hard work beats talent when talent doesn’t work hard. – Tim Notke",
    "Don’t watch the clock; do what it does. Keep going. – Sam Levenson",
    "Success doesn’t come from what you do occasionally, it comes from what you do consistently.",
    "The secret of getting ahead is getting started. – Mark Twain",
    "Opportunities are usually disguised as hard work, so most people don’t recognize them. – Ann Landers",

    "Work hard in silence, let success make the noise.",
    "Do something today that your future self will thank you for.",
    "Hard work spotlights the character of people. – Sam Ewing",
    "Without hustle, talent will only carry you so far. – Gary Vaynerchuk",
    "Don’t be afraid of hard work. Nothing worthwhile comes easily. – Theodore Roosevelt",
    "Work like someone is working 24 hours a day to take it away from you. – Mark Cuban",
    "Effort is grossly underrated. – Gary Vaynerchuk",
    "The difference between ordinary and extraordinary is that little extra. – Jimmy Johnson",
    "Go the extra mile, it’s never crowded.",
    "All growth depends upon activity. There is no development without effort. – Calvin Coolidge",

    "Success is where preparation and opportunity meet. – Bobby Unser",
    "Satisfaction lies in the effort, not in the attainment. – Mahatma Gandhi",
    "Success is no accident. It is hard work, perseverance, learning, and sacrifice. – Pelé",
    "Hard work never brings fatigue. It brings satisfaction. – Narendra Modi",
    "There are no shortcuts to any place worth going. – Beverly Sills",
    "The only way to achieve the impossible is to believe it is possible. – Charles Kingsleigh",
    "Start where you are. Use what you have. Do what you can. – Arthur Ashe",
    "Work hard, be kind, and amazing things will happen. – Conan O’Brien",
    "When you live for a strong purpose, then hard work isn’t an option. It’s a necessity.",
    "Plans are only good intentions unless they immediately degenerate into hard work. – Peter Drucker",

    "Without labor nothing prospers. – Sophocles",
    "Do not whine… Do not complain. Work harder. Spend more time alone. – Joan Didion",
    "Luck is a dividend of sweat. The more you sweat, the luckier you get. – Ray Kroc",
    "If people knew how hard I had to work to gain my mastery, it would not seem so wonderful at all. – Michelangelo",
    "The future depends on what you do today. – Mahatma Gandhi",
    "Perseverance is the hard work you do after you get tired of doing the hard work you already did. – Newt Gingrich",
    "Quality is never an accident. It is always the result of intelligent effort. – John Ruskin",
    "There is no substitute for hard work. – Thomas Edison",
    "Work hard and be proud of what you achieve.",
    "If you want something you’ve never had, you must be willing to do something you’ve never done.",

    "A dream doesn’t become reality through magic; it takes sweat, determination, and hard work. – Colin Powell",
    "Hard work compounds like interest, and the earlier you do it, the more time you have for the benefits to pay off. – Sam Altman",
    "The man who moves a mountain begins by carrying away small stones. – Confucius",
    "Hard work without talent is a shame, but talent without hard work is a tragedy. – Robert Half",
    "Work gives you meaning and purpose, and life is empty without it. – Stephen Hawking",
    "Success isn’t always about greatness. It’s about consistency. Consistent hard work leads to success. – Dwayne Johnson",
    "Do not wait to strike till the iron is hot; but make it hot by striking. – William Butler Yeats",
    "Work hard, stay humble, and trust the process.",
    "Effort and courage are not enough without purpose and direction. – John F. Kennedy",
    "Hard work is the price we must pay for success. – Vince Lombardi",

    "Discipline is the bridge between goals and accomplishment. – Jim Rohn",
    "The pain you feel today is the strength you’ll feel tomorrow.",
    "Work joyfully and peacefully, knowing that right thoughts and right efforts will inevitably bring about right results. – James Allen",
    "The only thing standing between you and outrageous success is continuous progress. – Dan Waldschmidt",
    "The only limit to our realization of tomorrow will be our doubts of today. – Franklin D. Roosevelt",
    "Hard work always pays off, whatever you do.",
    "You can’t cheat the grind, it knows how much you’ve invested.",
    "Energy and persistence conquer all things. – Benjamin Franklin",
    "If you train hard, you’ll not only be hard, you’ll be hard to beat. – Herschel Walker",
    "The key to success is action, and the essential in action is perseverance. – Sun Yat-sen",

    "Hard work makes you stronger. Laziness makes you weaker.",
    "You don’t get what you wish for. You get what you work for.",
    "Through hard work, perseverance, and a faith in God, you can live your dreams. – Ben Carson",
    "There is no elevator to success, you have to take the stairs.",
    "Hard work is an essential element in tracking down and perfecting a strategy or in executing it. – Charlie Munger",
    "The difference between try and triumph is just a little umph!",
    "The reward of a thing well done is to have done it. – Ralph Waldo Emerson",
    "The fruit of your own hard work is the sweetest. – Deepika Padukone",
    "Push yourself again and again. Don’t give an inch until the final buzzer sounds. – Larry Bird",
    "Do the hard jobs first. The easy jobs will take care of themselves. – Dale Carnegie",

    "Hard work is the formula for success.",
    "Don’t limit your challenges. Challenge your limits.",
    "Work hard, dream big, stay focused.",
    "A lot of hard work is hidden behind nice things.",
    "Striving for success without hard work is like trying to harvest where you haven’t planted. – David Bly",
    "Your work is discover your work and then with all your heart to give yourself to it. – Buddha",
    "Don’t be upset with the results you didn’t get from the work you didn’t do.",
    "To achieve great things, you need to work hard, take risks, and stay disciplined.",
    "Hard work is the foundation of all achievements worth remembering.",
    "Those who work hard today will shine tomorrow.",
]
